development:
  adapter: postgresql
  encoding: unicode
  database: carrierwave_example_development
  pool: 5
  username: reedns
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: carrierwave_example_development_test
  pool: 5
  username: reedns
