# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7fde96e82573fa685a264e8ba97bfa159e459ba871d304512e83156d04769c27ff8b807a40db99c79af92b605c78ff84a79453729b8e784479188c99fb52aa5

test:
  secret_key_base: 280af555fdeebd16f85372b65b5033fc4c61ba955ecfd87a19579a2d4a4baffe1f6156e5220c476207652afc94ce2f997f3bad30424107d9b939bfa24dc7b2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
